### ISSUE TITLE
Issue with exogenous input using pytorch backend

### ISSUE THREAD

**Issue by morgrothiel** [lululxvi/deepxde#1365]
I have had an issue with using exogenous input and PyTorch as backend. I tried to also run the Lorenz-problem example, but this also runs into an error. I do not experience the same issue when using tensorflow. I have not made any changes to the example code.

The error I get is: 
AttributeError: 'FNN' object has no attribute 'auxiliary_vars'

**Comment by lululxvi** [comment]
What is your DeepXDE version?

**Comment by xuelanghanbao** [comment]
> What is your DeepXDE version?

I have the same issue at deepxde 1.8.2, when I update deepxde to 1.9.2, there was no such error, but another error appeared:

```
 in Lorenz_Exogenous_Input_Inverse.gen_pde..Lorenz_system(x, y, ex)
    204 dy3_x = dde.grad.jacobian(y, x, i=2)
    205 return [
    206     dy1_x - self.C1 * (y2 - y1),
    207     dy2_x - y1 * (self.C2 - y3) + y2,
--> 208     dy3_x - y1 * y2 + self.C3 * y3 - ex,
    209 ]

File [c:\Users\admin\anaconda3\envs\pytorch2-0\lib\site-packages\torch\_tensor.py:970](file:///C:/Users/admin/anaconda3/envs/pytorch2-0/lib/site-packages/torch/_tensor.py:970), in Tensor.__array__(self, dtype)
    968     return handle_torch_function(Tensor.__array__, (self,), self, dtype=dtype)
    969 if dtype is None:
--> 970     return self.numpy()
    971 else:
    972     return self.numpy().astype(dtype, copy=False)

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

Which can be solved by manually converting ex to tensor, as shown below:

```python
def Lorenz_system(x, y, ex):
    y1, y2, y3 = y[:, 0:1], y[:, 1:2], y[:, 2:]
    dy1_x = dde.grad.jacobian(y, x, i=0)
    dy2_x = dde.grad.jacobian(y, x, i=1)
    dy3_x = dde.grad.jacobian(y, x, i=2)
    ex = bkd.from_numpy(ex)
    return [
        dy1_x - C1 * (y2 - y1),
        dy2_x - y1 * (C2 - y3) + y2,
        dy3_x - y1 * y2 + C3 * y3 - ex,
    ]
```
